import { z } from "zod";
import { zUuid, zMoney, zRequiredString, zPagination } from "@/lib/validation";

/**
 * Sales schemas. The cart the POS sends is fully re-validated here;
 * prices in the payload are treated as REQUESTS (price override) that
 * the service only honors if the role has the permission — the product's
 * real price is always re-read server-side.
 */

export const saleItemSchema = z.object({
  productId: zUuid,
  quantity: z.coerce.number().int().positive("Quantity must be at least 1."),
  /** Optional price override — requires sales:manage, else ignored */
  unitPriceOverride: zMoney.optional(),
  discountAmount: zMoney.default(0), // per-line, absolute
});

export const paymentSchema = z.object({
  method: z.enum(["CASH", "CARD", "BANK_TRANSFER", "STORE_CREDIT"]),
  amount: zMoney.refine((v) => v > 0, "Payment amount must be positive."),
  reference: z.string().trim().max(100).optional(),
});

export const createSaleSchema = z.object({
  /** Idempotency key generated by the POS — offline-ready (safe retries) */
  clientRef: zUuid,
  customerId: zUuid.optional(),        // absent = walk-in
  status: z.enum(["DRAFT", "COMPLETED"]).default("COMPLETED"),
  items: z.array(saleItemSchema).min(1, "The cart is empty.").max(100),
  globalDiscount: zMoney.default(0),
  /** Absent -> business default tax rate */
  taxRate: z.coerce.number().min(0).max(100).optional(),
  notes: z.string().trim().max(500).optional(),
  /** Required when completing; must cover total unless customer is registered */
  payments: z.array(paymentSchema).max(4).default([]),
});
export type CreateSaleInput = z.infer<typeof createSaleSchema>;

export const updateDraftSchema = createSaleSchema.omit({ clientRef: true }).extend({ id: zUuid });
export type UpdateDraftInput = z.infer<typeof updateDraftSchema>;

export const returnSchema = z.object({
  saleId: zUuid,
  items: z
    .array(z.object({ saleItemId: zUuid, quantity: z.coerce.number().int().positive() }))
    .min(1, "Select at least one item to return."),
  reason: zRequiredString("Reason", 200),
  refundMethod: z.enum(["CASH", "STORE_CREDIT"]).default("CASH"),
});
export type ReturnInput = z.infer<typeof returnSchema>;

export const saleFilterSchema = zPagination.extend({
  q: z.string().trim().max(100).optional(),          // sale number / customer
  status: z.enum(["DRAFT", "COMPLETED", "PARTIALLY_RETURNED", "RETURNED", "VOIDED", "CANCELLED"]).optional(),
  paymentStatus: z.enum(["PENDING", "PARTIAL", "PAID", "REFUNDED"]).optional(),
  customerId: zUuid.optional(),
  from: z.coerce.date().optional(),
  to: z.coerce.date().optional(),
  sortDir: z.enum(["asc", "desc"]).default("desc"),
});
export type SaleFilter = z.infer<typeof saleFilterSchema>;

/** POS product search (server action) */
export const posSearchSchema = z.object({
  q: z.string().trim().min(1).max(100),
});
